server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: wine-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gitluozb/springcloud_config.git
          search-paths: wine-config
          username: gitluozb
          password: seeyouagain927

